version: '3'

volumes:
  pgdata: {}

services:
  db:
    image: postgres:15.3
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data:Z
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - ./data:/tmp/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      FLASK_DEBUG: 1
    ports:
      - "5001:5001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
